export const hardcodedRequests = {
  requests: [
    {
      id: '234f961d-06a6-4e27-befb-636ea99044d3',
      datetimeCreated: '2020-12-17',
      locationType: 'public area',
      name: 'Lorem Ipsum',
      email: 'aaa@aa.aa',
      appliance: 'washing machine',
      houseNo: '123',
      street: 'Some St',
      town: 'Some Town',
      postcode: 'ST1 2AB',
      notes: 'in the back alley',
      errandType: 'collection',
      completed: true,
      datetimeCompleted: '0000-00-00 00:00:00',
      longitude: '',
      latitude: '',
      driverId: '',
      waitingList: false,
      assignedDate: '',
    },
    {
      id: '456f961d-06a6-4e27-befb-636ea99044d3',
      datetimeCreated: '2020-12-17',
      errandType: 'collection',
      name: 'Dolor Sit Amet',
      email: 'aaa@aa.aa',
      houseNo: '45',
      street: 'Some Other St',
      town: 'Some Other Town',
      postcode: 'ST2 3CD',
      appliance: 'fridge',
      locationType: 'private property',
      notes: '',
      completed: false,
      datetimeCompleted: '0000-00-00 00:00:00',
      longitude: '',
      latitude: '',
      driverId: '',
      waitingList: false,
      assignedDate: '',
    },
    {
      id: '686f961d-06a6-4e27-befb-636ea99044d3',
      datetimeCreated: '2020-12-17',
      errandType: 'collection',
      name: 'John Doe',
      email: 'aaa@aa.aa',
      houseNo: '67',
      street: 'Lorem Ipsum',
      town: 'Dolor sit amet',
      postcode: 'ABC 123',
      appliance: 'dish washer',
      locationType: 'private property',
      notes: 'no parking in front',
      completed: false,
      datetimeCompleted: '0000-00-00 00:00:00',
      longitude: '',
      latitude: '',
      driverId: '',
      waitingList: false,
      assignedDate: '',
    },
    {
      id: '212f961d-06a6-4e27-befb-636ea99044d3',
      datetimeCreated: '2020-12-18',
      errandType: 'collection',
      name: 'Mary Newman',
      email: 'aaa@aa.aa',
      houseNo: '89',
      street: 'Adipiscing',
      town: 'Consectetur',
      postcode: 'ABC 123',
      appliance: 'dish washer',
      locationType: 'private property',
      notes: 'no parking in front',
      completed: false,
      datetimeCompleted: '0000-00-00 00:00:00',
      longitude: '',
      latitude: '',
      driverId: '',
      waitingList: false,
      assignedDate: '',
    },
  ],
  users: [
    {
      id: 1,
      permissionLevel: 'admin',
      name: 'Dorota',
      email: 'ccc@cc.cc',
      password: 'loremipsum',
    },
    {
      id: 2,
      permissionLevel: 'admin',
      name: 'Dan',
      email: 'ddd@dd.dd',
      password: 'loremipsum',
    },
    {
      id: 3,
      permissionLevel: 'driver',
      name: 'Bob',
      email: 'bbb@bb.bb',
      password: 'loremipsum',
    },
    {
      id: 4,
      permissionLevel: 'driver',
      name: 'Alice',
      email: 'aaa@aa.aa',
      password: 'loremipsum',
    },
  ],
};
